# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
